<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.475">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Modélisation d’une variable quantitative - Application n°3</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Modélisation d’une variable quantitative</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./MOD1_Yquanti_001.html">
 <span class="menu-text">Introduction</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./MOD1_Yquanti_004.html">
 <span class="menu-text">Cours d’économétrie</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./MOD1_Yquanti_002.html">
 <span class="menu-text">Application n°1</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./MOD1_Yquanti_003.html">
 <span class="menu-text">Application n°2</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./MOD1_Yquanti_005.html" aria-current="page">
 <span class="menu-text">Application n°3</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#a.-donnees" id="toc-a.-donnees" class="nav-link active" data-scroll-target="#a.-donnees">A. DONNEES</a>
  <ul class="collapse">
  <li><a href="#importation" id="toc-importation" class="nav-link" data-scroll-target="#importation">Importation</a></li>
  <li><a href="#liste-des-variables" id="toc-liste-des-variables" class="nav-link" data-scroll-target="#liste-des-variables">Liste des variables</a></li>
  <li><a href="#fonds-de-carte" id="toc-fonds-de-carte" class="nav-link" data-scroll-target="#fonds-de-carte">Fonds de carte</a></li>
  </ul></li>
  <li><a href="#b.-analyse-du-benin" id="toc-b.-analyse-du-benin" class="nav-link" data-scroll-target="#b.-analyse-du-benin">B. ANALYSE DU BENIN</a>
  <ul class="collapse">
  <li><a href="#structure-du-menage" id="toc-structure-du-menage" class="nav-link" data-scroll-target="#structure-du-menage">STRUCTURE DU MENAGE</a></li>
  <li><a href="#attributs-du-chef-de-menage" id="toc-attributs-du-chef-de-menage" class="nav-link" data-scroll-target="#attributs-du-chef-de-menage">ATTRIBUTS DU CHEF DE MENAGE</a></li>
  <li><a href="#posistion-geographique" id="toc-posistion-geographique" class="nav-link" data-scroll-target="#posistion-geographique">POSISTION GEOGRAPHIQUE</a></li>
  <li><a href="#accessibilité-communale" id="toc-accessibilité-communale" class="nav-link" data-scroll-target="#accessibilité-communale">Accessibilité communale</a></li>
  <li><a href="#accessibilité-départementale" id="toc-accessibilité-départementale" class="nav-link" data-scroll-target="#accessibilité-départementale">Accessibilité départementale</a></li>
  <li><a href="#accessibilité-nationale" id="toc-accessibilité-nationale" class="nav-link" data-scroll-target="#accessibilité-nationale">Accessibilité Nationale</a></li>
  <li><a href="#synthese" id="toc-synthese" class="nav-link" data-scroll-target="#synthese">SYNTHESE</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Application n°3</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="cell">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr, <span class="at">quietly =</span> <span class="cn">TRUE</span>,<span class="at">warn.conflicts =</span> F)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car,<span class="at">warn.conflicts =</span> F,<span class="at">quietly=</span>T)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mapsf)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RColorBrewer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>L’objectif de la présente analyse est d’analyser un tableau de <strong>données individuelles</strong> permettant de décrire le niveau de vie des ménages en fonction d’un certain nombre d’indicateurs endogènes ou exogènes.</p>
<section id="a.-donnees" class="level2">
<h2 class="anchored" data-anchor-id="a.-donnees">A. DONNEES</h2>
<p>Le jeu de données est un échantillon de variables relatives aux ménages du Bénin lors du RP 2013. Il s’agit plus précisément d’une extraction par tirage au sort de 100 ménages dans chacun des 546 arrondissements du Bénin. Le tirage au sort a été effectué en se limitant aux ménages composés d’au moins deux personnes, dont le chef de ménage est marié ou en union libre et dont les variables chosies ne comportent pas de valeurs manquantes ou non renseignés. La base de sondage se compose donc d’1.305 millions de ménages sur les 2 millions que compte le Bénin à cette date. L’échantillon comporte exactement 54600 lignes (100 pour chacun des 546 arrondissements).</p>
<p>Les variables ont été anonymisées en supprimant le numéro d’identification des ménages du recensement et en le remplaçant par le code de l’arrondissement suivi d’un chiffre de 001 à 100. Les variables les plus discriminantes ont vu leur nombre de modalité réduit.</p>
<section id="importation" class="level3">
<h3 class="anchored" data-anchor-id="importation">Importation</h3>
<p>On importe les données</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>don <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"BEN-MEN-2013/BEN-MEN-2013-SAMPLE.RDS"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(don), <span class="at">caption =</span> <span class="st">"Premières lignes du tableau"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<caption>Premières lignes du tableau</caption>
<colgroup>
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 3%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">ID</th>
<th style="text-align: right;">WGT</th>
<th style="text-align: left;">DEP</th>
<th style="text-align: left;">DEP_NAME</th>
<th style="text-align: left;">COM</th>
<th style="text-align: left;">COM_NAME</th>
<th style="text-align: left;">ARR</th>
<th style="text-align: left;">ARR_NAME</th>
<th style="text-align: right;">URBA</th>
<th style="text-align: right;">DEP_CHEF</th>
<th style="text-align: right;">COM_CHEF</th>
<th style="text-align: right;">COM_CHEF_DIST</th>
<th style="text-align: right;">DEP_CHEF_DIST</th>
<th style="text-align: right;">NAT_CHEF_DIST</th>
<th style="text-align: left;">statoc</th>
<th style="text-align: right;">tailmen</th>
<th style="text-align: left;">locnais</th>
<th style="text-align: right;">datnais</th>
<th style="text-align: right;">age</th>
<th style="text-align: left;">sexe</th>
<th style="text-align: left;">etud5</th>
<th style="text-align: left;">radio</th>
<th style="text-align: left;">telev</th>
<th style="text-align: left;">hifi</th>
<th style="text-align: left;">parab</th>
<th style="text-align: left;">magne</th>
<th style="text-align: left;">cddvd</th>
<th style="text-align: left;">frigo</th>
<th style="text-align: left;">cuisi</th>
<th style="text-align: left;">foyam</th>
<th style="text-align: left;">ferre</th>
<th style="text-align: left;">clima</th>
<th style="text-align: left;">venti</th>
<th style="text-align: left;">lit</th>
<th style="text-align: left;">matel</th>
<th style="text-align: left;">faumo</th>
<th style="text-align: left;">ordi</th>
<th style="text-align: left;">inter</th>
<th style="text-align: left;">elgen</th>
<th style="text-align: left;">bicyc</th>
<th style="text-align: left;">motoc</th>
<th style="text-align: left;">voitu</th>
<th style="text-align: left;">barqu</th>
<th style="text-align: left;">telfix</th>
<th style="text-align: left;">telmob</th>
<th style="text-align: right;">equip_tot</th>
<th style="text-align: right;">equip_acp</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">01101_001</td>
<td style="text-align: right;">37.58</td>
<td style="text-align: left;">01</td>
<td style="text-align: left;">ALIBORI</td>
<td style="text-align: left;">011</td>
<td style="text-align: left;">BANIKOARA</td>
<td style="text-align: left;">01101</td>
<td style="text-align: left;">FOUNOUNGO</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23.30885</td>
<td style="text-align: right;">55.21384</td>
<td style="text-align: right;">572.8043</td>
<td style="text-align: left;">PropFam</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">011</td>
<td style="text-align: right;">1987</td>
<td style="text-align: right;">26</td>
<td style="text-align: left;">M</td>
<td style="text-align: left;">1.Aucun</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-1.1496591</td>
</tr>
<tr class="even">
<td style="text-align: left;">39</td>
<td style="text-align: left;">01101_002</td>
<td style="text-align: right;">37.58</td>
<td style="text-align: left;">01</td>
<td style="text-align: left;">ALIBORI</td>
<td style="text-align: left;">011</td>
<td style="text-align: left;">BANIKOARA</td>
<td style="text-align: left;">01101</td>
<td style="text-align: left;">FOUNOUNGO</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23.30885</td>
<td style="text-align: right;">55.21384</td>
<td style="text-align: right;">572.8043</td>
<td style="text-align: left;">PropFam</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">011</td>
<td style="text-align: right;">1978</td>
<td style="text-align: right;">35</td>
<td style="text-align: left;">M</td>
<td style="text-align: left;">1.Aucun</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">-0.6338360</td>
</tr>
<tr class="odd">
<td style="text-align: left;">45</td>
<td style="text-align: left;">01101_003</td>
<td style="text-align: right;">37.58</td>
<td style="text-align: left;">01</td>
<td style="text-align: left;">ALIBORI</td>
<td style="text-align: left;">011</td>
<td style="text-align: left;">BANIKOARA</td>
<td style="text-align: left;">01101</td>
<td style="text-align: left;">FOUNOUNGO</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23.30885</td>
<td style="text-align: right;">55.21384</td>
<td style="text-align: right;">572.8043</td>
<td style="text-align: left;">PropFam</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">011</td>
<td style="text-align: right;">1982</td>
<td style="text-align: right;">31</td>
<td style="text-align: left;">M</td>
<td style="text-align: left;">1.Aucun</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">-0.3559969</td>
</tr>
<tr class="even">
<td style="text-align: left;">76</td>
<td style="text-align: left;">01101_004</td>
<td style="text-align: right;">37.58</td>
<td style="text-align: left;">01</td>
<td style="text-align: left;">ALIBORI</td>
<td style="text-align: left;">011</td>
<td style="text-align: left;">BANIKOARA</td>
<td style="text-align: left;">01101</td>
<td style="text-align: left;">FOUNOUNGO</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23.30885</td>
<td style="text-align: right;">55.21384</td>
<td style="text-align: right;">572.8043</td>
<td style="text-align: left;">PropInd</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">011</td>
<td style="text-align: right;">1970</td>
<td style="text-align: right;">43</td>
<td style="text-align: left;">M</td>
<td style="text-align: left;">1.Aucun</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">-0.0904709</td>
</tr>
<tr class="odd">
<td style="text-align: left;">91</td>
<td style="text-align: left;">01101_005</td>
<td style="text-align: right;">37.58</td>
<td style="text-align: left;">01</td>
<td style="text-align: left;">ALIBORI</td>
<td style="text-align: left;">011</td>
<td style="text-align: left;">BANIKOARA</td>
<td style="text-align: left;">01101</td>
<td style="text-align: left;">FOUNOUNGO</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23.30885</td>
<td style="text-align: right;">55.21384</td>
<td style="text-align: right;">572.8043</td>
<td style="text-align: left;">PropFam</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">011</td>
<td style="text-align: right;">1983</td>
<td style="text-align: right;">30</td>
<td style="text-align: left;">M</td>
<td style="text-align: left;">1.Aucun</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">-1.1499543</td>
</tr>
<tr class="even">
<td style="text-align: left;">115</td>
<td style="text-align: left;">01101_006</td>
<td style="text-align: right;">37.58</td>
<td style="text-align: left;">01</td>
<td style="text-align: left;">ALIBORI</td>
<td style="text-align: left;">011</td>
<td style="text-align: left;">BANIKOARA</td>
<td style="text-align: left;">01101</td>
<td style="text-align: left;">FOUNOUNGO</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23.30885</td>
<td style="text-align: right;">55.21384</td>
<td style="text-align: right;">572.8043</td>
<td style="text-align: left;">PropFam</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">011</td>
<td style="text-align: right;">1988</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">M</td>
<td style="text-align: left;">1.Aucun</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">-0.2158661</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(don<span class="sc">$</span>WGT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1305188</code></pre>
</div>
</div>
</section>
<section id="liste-des-variables" class="level3">
<h3 class="anchored" data-anchor-id="liste-des-variables">Liste des variables</h3>
<p>Le tableau comporte 47 variables</p>
<ul>
<li><p><strong>STRATES</strong></p></li>
<li><p>ID : identifiant anonyme du ménage</p></li>
<li><p>WGT : poids du ménage</p></li>
<li><p><strong>POSITION GEOGRAPHIQUE</strong></p></li>
<li><p>DEP : code du département</p></li>
<li><p>DEP_NAME : nom du département</p></li>
<li><p>COM : code de la commune</p></li>
<li><p>COM_NAME : nom de la commune</p></li>
<li><p>ARR : code de l’arrondissement</p></li>
<li><p>ARR_NAME : nom de l’arrondissement</p></li>
<li><p>URBA : statut de l’arrondissement (0 = rural, 1 = urbain)</p></li>
<li><p>DEP_CHEF : arrondissement situé au chef-lieu du département (0 = non, 1 = oui)</p></li>
<li><p>COM_CHEF : arrondissement situé au chef-lieu de la commune (0 = non, 1 = oui)</p></li>
<li><p>COM_CHEF_DIST : distance de l’arrondissement au chef-lieu de sa commune (en km)</p></li>
<li><p>DEP_CHEF_DIST : distance de l’arrondissement au chef-lieu de son département (en km)</p></li>
<li><p>NAT_CHEF_DIST : distance de l’arrondissement à l’aéroport de Cotonu (en km)</p></li>
<li><p><strong>STRUCTURE DU MENAGE</strong></p></li>
<li><p>statoc : statut d’occupation (Propriété individuelle ou familiale, locataire, autre)</p></li>
<li><p>tailmen : nombre de personnes recensées dans le ménage</p></li>
<li><p><strong>ATTRIBUTS DU CHEF DE MENAGE</strong></p></li>
<li><p>locnais : code de la commune de naissance (ou du département ou du pays étranger)</p></li>
<li><p>datnais : année de naissance</p></li>
<li><p>age : âge en différence de millésime</p></li>
<li><p>sexe : sexe</p></li>
<li><p>etud5 : niveau d’étude maximal (ramené à 5 modalités)</p></li>
<li><p><strong>EQUIPEMENT DU MENAGE (présence ou absence) </strong></p></li>
<li><p>radio : poste de radio</p></li>
<li><p>telev : poste de télévision</p></li>
<li><p>hifi : chaîne HIFI<br>
</p></li>
<li><p>parab : parabole</p></li>
<li><p>magne : magnetoscope</p></li>
<li><p>cddvd : lecteur de CD-DVD<br>
</p></li>
<li><p>frigo : réfrigérateur<br>
</p></li>
<li><p>cuisi : cuisinière<br>
</p></li>
<li><p>foyam : foyer aménagé<br>
</p></li>
<li><p>ferre : fer à repasser<br>
</p></li>
<li><p>clima : climatiseur<br>
</p></li>
<li><p>venti : betilateur<br>
</p></li>
<li><p>lit : lit<br>
</p></li>
<li><p>matel : matelas<br>
</p></li>
<li><p>faumo : fauteuril moderne<br>
</p></li>
<li><p>ordi : ordinateur<br>
</p></li>
<li><p>inter : accès internet<br>
</p></li>
<li><p>elgen : générateur électrique<br>
</p></li>
<li><p>bicyc : bicyclette<br>
</p></li>
<li><p>motoc : motcyclette<br>
</p></li>
<li><p>voitu : coiture<br>
</p></li>
<li><p>barqu : barque, pirogue<br>
</p></li>
<li><p>telfix: téléphone fixe (au moins une ligne)<br>
</p></li>
<li><p>telmob: téléphone mobile (au moins un abonnement)</p></li>
<li><p><strong>SYNTHESE DES EQUIPEMENTS</strong></p></li>
<li><p>equip_tot : nombre total d’équipements différents (0 à 24)</p></li>
<li><p>equip_acp : coordonnées sur le 1er axe factoriel d’une ACP sur les 24 équipements.</p></li>
</ul>
</section>
<section id="fonds-de-carte" class="level3">
<h3 class="anchored" data-anchor-id="fonds-de-carte">Fonds de carte</h3>
<p>Nous disposons de quatre fonds de carte correspondant au découpage du Bénin à chacune des échelles d’analyse</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>BEN0<span class="ot">&lt;-</span><span class="fu">readRDS</span>(<span class="st">"BEN-MEN-2013/BEN-ADM0.RDS"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>BEN1<span class="ot">&lt;-</span><span class="fu">readRDS</span>(<span class="st">"BEN-MEN-2013/BEN-ADM1-DIST.RDS"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>BEN2<span class="ot">&lt;-</span><span class="fu">readRDS</span>(<span class="st">"BEN-MEN-2013/BEN-ADM2-DIST.RDS"</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>BEN3<span class="ot">&lt;-</span><span class="fu">readRDS</span>(<span class="st">"BEN-MEN-2013/BEN-ADM3-DIST.RDS"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Il permet d’ores et déjà de repérer la position des départements, communes et arrondissements.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mf_map</span>(BEN1, <span class="at">type=</span><span class="st">"typo"</span>,<span class="at">var=</span><span class="st">"DEP_NAME"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mf_map</span>(BEN3, <span class="at">type=</span><span class="st">"base"</span>,<span class="at">col=</span><span class="cn">NA</span>,<span class="at">border=</span><span class="st">"white"</span>,<span class="at">lwd=</span><span class="fl">0.1</span>,<span class="at">add=</span>T)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mf_map</span>(BEN2, <span class="at">type=</span><span class="st">"base"</span>,<span class="at">col=</span><span class="cn">NA</span>,<span class="at">border=</span><span class="st">"black"</span>,<span class="at">lwd=</span><span class="fl">0.5</span>,<span class="at">add=</span>T)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mf_map</span>(BEN1, <span class="at">type=</span><span class="st">"base"</span>,<span class="at">col=</span><span class="cn">NA</span>,<span class="at">border=</span><span class="st">"black"</span>,<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">add=</span>T)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mf_layout</span>(<span class="at">title =</span> <span class="st">"Carte administrative du Bénin en 2013"</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">credits =</span> <span class="st">"Source : EE CIST 2023"</span>,<span class="at">frame =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MOD1_Yquanti_005_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="576"></p>
</div>
</div>
</section>
</section>
<section id="b.-analyse-du-benin" class="level2">
<h2 class="anchored" data-anchor-id="b.-analyse-du-benin">B. ANALYSE DU BENIN</h2>
<p>On choisit de retenir l’ensemble des ménages de l’échantillon et de prendre comme variable dépendante (Y) le nombre total d’équipements dont ils disposent. La valeur minimale est de 0 et la valeur maximale de 24. La distribution est fortement dissymétrique à gauche ce qui est logique</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>sel<span class="ot">&lt;-</span>don</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>sel<span class="sc">$</span>equip<span class="ot">&lt;-</span>sel<span class="sc">$</span>equip_tot</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(sel<span class="sc">$</span>equip, </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">24</span>,<span class="dv">1</span>),</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">col=</span><span class="st">"lightyellow"</span>,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">probability =</span> T,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Equipements des ménages du Bénin en 2013"</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">sub =</span> <span class="st">"Source : RP2013, INS Bénin, échantillon stratifié par arrondissements"</span>,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Nombre d'équipements"</span>,</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span> <span class="st">"Probabilité"</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>     )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MOD1_Yquanti_005_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sel<span class="sc">$</span>equip)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  0.000   2.000   3.000   4.049   5.000  24.000 </code></pre>
</div>
</div>
<ul>
<li><strong>Commentaire</strong> : le nombre moyen d’équipement des ménages est environ de 4 mais la médiane est de 3 et le mode de 0. La distribution est donc très fortement dissymétrique à gauche avec un grand nombre de ménages n’ayant que des équipements de base (radio, bicyclette, téléphone mobile,) et une très petite minorité accédant à tous les équipements y compris les plus rares et les plus coûteux (connexion internet, ordinateur, …)</li>
</ul>
<section id="structure-du-menage" class="level3">
<h3 class="anchored" data-anchor-id="structure-du-menage">STRUCTURE DU MENAGE</h3>
<p>On peut modéliser tout d’abord l’effet de variables structurelles liées à la taille du ménage et au statut d’occupation du logement.</p>
<section id="taille-du-ménage" class="level4">
<h4 class="anchored" data-anchor-id="taille-du-ménage">Taille du ménage</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>X<span class="ot">&lt;-</span><span class="fu">log</span>(sel<span class="sc">$</span>tailmen)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>Y<span class="ot">&lt;-</span>sel<span class="sc">$</span>equip</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>nameX<span class="ot">&lt;-</span><span class="st">"Taille du ménage (log)"</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>nameY<span class="ot">&lt;-</span><span class="st">"Nombre d'équipements (0 à 24) "</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>titre<span class="ot">&lt;-</span><span class="st">"Equipement des ménages du Bénin en 2013"</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>source<span class="ot">&lt;-</span><span class="st">"Source : RP2013, INS Bénin"</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>mod<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(X,Y ,</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">main=</span>titre,</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">sub =</span> source,</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab=</span>nameX,</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab=</span>nameY)</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(mod, <span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MOD1_Yquanti_005_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.5649 -2.2868 -0.7923  1.2188 19.8085 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  2.80348    0.04569   61.35   &lt;2e-16 ***
X            0.71331    0.02492   28.63   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.264 on 54598 degrees of freedom
Multiple R-squared:  0.01479,   Adjusted R-squared:  0.01477 
F-statistic: 819.6 on 1 and 54598 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><strong>Commentaire</strong> : Relation significative mais à très faible pouvoir explicatif. Le nombre d’équipement augmente de 0.7 chaque fois que le logarithme du nombre de personnes présentes augmente de 1. Un ménage de 10 personnes devrait donc avoir 2.8 + 0.7*log(10) = 4.4 équipements.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fl">2.8+0.7</span><span class="sc">*</span><span class="fu">log</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.41181</code></pre>
</div>
</div>
</section>
<section id="statut-doccupation" class="level4">
<h4 class="anchored" data-anchor-id="statut-doccupation">Statut d’occupation</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>X<span class="ot">&lt;-</span>sel<span class="sc">$</span>statoc</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>Y<span class="ot">&lt;-</span>sel<span class="sc">$</span>equip</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>nameX<span class="ot">&lt;-</span><span class="st">"Statut d'occupation"</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>nameY<span class="ot">&lt;-</span><span class="st">"Nombre d'équipements (0 à 24) "</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>titre<span class="ot">&lt;-</span><span class="st">"Equipement des ménages du Bénin en 2013"</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>source<span class="ot">&lt;-</span><span class="st">"Source : RP2013, INS Bénin"</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>mod<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Y<span class="sc">~</span>X, </span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">main=</span>titre,</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">sub =</span> source,</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab=</span>nameX,</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab=</span>nameY,</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">col=</span><span class="st">"lightyellow"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MOD1_Yquanti_005_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.4322 -2.3494 -0.5342  1.4658 19.6506 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.34941    0.02382  182.56  &lt; 2e-16 ***
XPropFam    -0.81522    0.03009  -27.10  &lt; 2e-16 ***
XAutre      -0.48134    0.07372   -6.53 6.65e-11 ***
XLocat       2.08282    0.05362   38.84  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.191 on 54596 degrees of freedom
Multiple R-squared:  0.05882,   Adjusted R-squared:  0.05877 
F-statistic:  1137 on 3 and 54596 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><strong>Commentaire</strong> : Avantage significatif des locataires (p &lt;0.001) qui ont en moyenne 2 équipements de plus que les propriétaires individuels. Mais cela révèle sans doute indirectement un effet urbain-rural.</li>
</ul>
</section>
</section>
<section id="attributs-du-chef-de-menage" class="level3">
<h3 class="anchored" data-anchor-id="attributs-du-chef-de-menage">ATTRIBUTS DU CHEF DE MENAGE</h3>
<p>Une seconde série de caractéristique concernant les attributs du chef de ménage permet de tester d’autres reltions.</p>
<section id="sexe" class="level4">
<h4 class="anchored" data-anchor-id="sexe">Sexe</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>X<span class="ot">&lt;-</span>sel<span class="sc">$</span>sexe</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>Y<span class="ot">&lt;-</span>sel<span class="sc">$</span>equip</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>nameX<span class="ot">&lt;-</span><span class="st">"Sexe"</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>nameY<span class="ot">&lt;-</span><span class="st">"Nombre d'équipements (0 à 24) "</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>titre<span class="ot">&lt;-</span><span class="st">"Equipement des ménages du Bénin en 2013"</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>source<span class="ot">&lt;-</span><span class="st">"Source : RP2013, INS Bénin"</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>mod<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Y<span class="sc">~</span>X, </span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">main=</span>titre,</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">sub =</span> source,</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab=</span>nameX,</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab=</span>nameY,</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">col=</span><span class="st">"lightyellow"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MOD1_Yquanti_005_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.3115 -2.3115 -0.6331  1.3669 20.3669 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.31151    0.01506  286.31   &lt;2e-16 ***
XF          -1.67845    0.03807  -44.08   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.232 on 54598 degrees of freedom
Multiple R-squared:  0.03437,   Adjusted R-squared:  0.03435 
F-statistic:  1943 on 1 and 54598 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><strong>Commentaire</strong> : Les ménages dont le chef est une femme ont en moyenne 1.7 équipements de moins que les ménages dont le chef est un homme (4.3). La différence est significative.</li>
</ul>
</section>
<section id="classe-dâge" class="level4">
<h4 class="anchored" data-anchor-id="classe-dâge">Classe d’âge</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>sel<span class="sc">$</span>age5<span class="ot">&lt;-</span><span class="fu">cut</span>(sel<span class="sc">$</span>age, <span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">18</span>,<span class="dv">29</span>,<span class="dv">39</span>,<span class="dv">49</span>,<span class="dv">59</span>,<span class="dv">100</span>),<span class="at">include.lowest =</span> T)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(sel<span class="sc">$</span>age5)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"18-29"</span>, <span class="st">"30-39"</span>,<span class="st">"40-49"</span>,<span class="st">"50-59"</span>,<span class="st">"60+"</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>X<span class="ot">&lt;-</span>sel<span class="sc">$</span>age5</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>Y<span class="ot">&lt;-</span>sel<span class="sc">$</span>equip</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>nameX<span class="ot">&lt;-</span><span class="st">"Classe d'âge"</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>nameY<span class="ot">&lt;-</span><span class="st">"Nombre d'équipements (0 à 24) "</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>titre<span class="ot">&lt;-</span><span class="st">"Equipement des ménages du Bénin en 2013"</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>source<span class="ot">&lt;-</span><span class="st">"Source : RP2013, INS Bénin"</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>mod<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Y<span class="sc">~</span>X, </span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">main=</span>titre,</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">sub =</span> source,</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab=</span>nameX,</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab=</span>nameY,</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>        <span class="at">col=</span><span class="st">"lightyellow"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MOD1_Yquanti_005_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X)

Residuals:
   Min     1Q Median     3Q    Max 
-4.286 -2.218 -0.752  1.493 19.796 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  3.75199    0.03470 108.134   &lt;2e-16 ***
X30-39       0.46621    0.04292  10.862   &lt;2e-16 ***
X40-49       0.53391    0.04509  11.840   &lt;2e-16 ***
X50-59       0.45242    0.05097   8.876   &lt;2e-16 ***
X60+        -0.24495    0.05008  -4.891    1e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.276 on 54595 degrees of freedom
Multiple R-squared:  0.007785,  Adjusted R-squared:  0.007713 
F-statistic: 107.1 on 4 and 54595 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><strong>Commentaire</strong> : Relation significative mais à très faible pouvoir explicatif. Elle met en valeur le fait que les ménages les moins bien équipés sont ceux dont le chef est très jeune (moins de 30 ans) ou très âgé (plus de 60 ans).</li>
</ul>
</section>
<section id="niveau-détude" class="level4">
<h4 class="anchored" data-anchor-id="niveau-détude">Niveau d’étude</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>X<span class="ot">&lt;-</span>sel<span class="sc">$</span>etud5</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>Y<span class="ot">&lt;-</span>sel<span class="sc">$</span>equip</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>nameX<span class="ot">&lt;-</span><span class="st">"Niveau d'étude"</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>nameY<span class="ot">&lt;-</span><span class="st">"Nombre d'équipements (0 à 24) "</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>titre<span class="ot">&lt;-</span><span class="st">"Equipement des ménages du Bénin en 2013"</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>source<span class="ot">&lt;-</span><span class="st">"Source : RP2013, INS Bénin"</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>mod<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Y<span class="sc">~</span>X, </span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">main=</span>titre,</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">sub =</span> source,</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab=</span>nameX,</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab=</span>nameY,</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">col=</span><span class="st">"lightyellow"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MOD1_Yquanti_005_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X)

Residuals:
    Min      1Q  Median      3Q     Max 
-9.5163 -2.1405 -0.3599  1.4995 19.8595 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    3.14052    0.01590  197.47   &lt;2e-16 ***
X2.Primaire    1.35999    0.03236   42.03   &lt;2e-16 ***
X3.Secondaire  3.21940    0.03682   87.44   &lt;2e-16 ***
X4.Supérieur   6.37579    0.07843   81.30   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.946 on 54596 degrees of freedom
Multiple R-squared:  0.1974,    Adjusted R-squared:  0.1974 
F-statistic:  4477 on 3 and 54596 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><strong>Commentaire</strong> : Relation très significative et à très fort pouvoir explicatif comparée aux précédentes (r2 = 19.7%). Il s’agit du facteur le plus déterminant parmi ceux qui ont été retenus. Le niveau d’étude sert évidemment de proxy à d’autres variables telles que le revenu, la situation professionnelle, etc.</li>
</ul>
</section>
</section>
<section id="posistion-geographique" class="level3">
<h3 class="anchored" data-anchor-id="posistion-geographique">POSISTION GEOGRAPHIQUE</h3>
<p>Nous proposons maintenant une suite d’analyse portant sur les déterminants géographiques en distinguant deux cas selon que la variable explicative est catégorielle ou selon qu’elle correspond à un effect continu d’éloignement.</p>
<section id="déterminants-territoriaux" class="level4">
<h4 class="anchored" data-anchor-id="déterminants-territoriaux">Déterminants territoriaux</h4>
<p>Les <strong>déterminants territoriaux</strong> correspondent au cas où la variable explicative est <em>catégorielle</em> et où l’effet sur le ménage est lié à son <em>appartenance</em> à un type d’espace. Ceci nous permet d’identifier trois variables :</p>
<ul>
<li>URBA : l’arrondissement où le ménage est situé est-il déclaré “rural” ou “urbain” par l’état ?</li>
<li>DEF_CHEF : l’arrondissement où le ménage est situé est-il le siège d’un chef-lieu de département</li>
<li>COM_CHEF : l’arrondissement où le ménage est situé est-il le siège d’un chef-lieu de commune</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>map0<span class="ot">&lt;-</span>BEN0</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>map1<span class="ot">&lt;-</span>BEN1</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>map2<span class="ot">&lt;-</span>BEN2</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>map3<span class="ot">&lt;-</span>BEN3</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>map3<span class="sc">$</span>URBA<span class="ot">&lt;-</span><span class="fu">as.factor</span>(map3<span class="sc">$</span>URBA)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(map3<span class="sc">$</span>URBA)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"Rural"</span>,<span class="st">"Urbain"</span>)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>map2ctr<span class="ot">&lt;-</span><span class="fu">st_centroid</span>(map3[map3<span class="sc">$</span>COM_CHEF<span class="sc">==</span><span class="dv">1</span> <span class="sc">&amp;</span> map3<span class="sc">$</span>DEP_CHEF<span class="sc">==</span><span class="dv">0</span>,])</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>map1ctr<span class="ot">&lt;-</span><span class="fu">st_centroid</span>(map3[ map3<span class="sc">$</span>DEP_CHEF<span class="sc">==</span><span class="dv">1</span>,])</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="fu">mf_map</span>(map3,<span class="at">type=</span><span class="st">"typo"</span>,<span class="at">var=</span><span class="st">"URBA"</span>,<span class="at">pal=</span><span class="fu">c</span>(<span class="st">"lightyellow"</span>,<span class="st">"orange"</span>), <span class="at">border=</span><span class="st">"gray"</span>,<span class="at">lwd=</span><span class="fl">0.3</span>,<span class="at">leg_title =</span> <span class="st">"Type d'espace"</span>)</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="fu">mf_map</span>(map2,<span class="at">type=</span><span class="st">"base"</span>,<span class="at">col=</span><span class="cn">NA</span>, <span class="at">border=</span><span class="st">"black"</span>,<span class="at">lwd=</span><span class="dv">1</span>, <span class="at">add=</span>T)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="fu">mf_map</span>(map1,<span class="at">type=</span><span class="st">"base"</span>,<span class="at">col=</span><span class="cn">NA</span>, <span class="at">border=</span><span class="st">"black"</span>,<span class="at">lwd=</span><span class="dv">2</span>, <span class="at">add=</span>T)</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a><span class="fu">mf_map</span>(map2ctr,<span class="at">type=</span><span class="st">"base"</span>,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">col=</span><span class="st">"blue"</span>,<span class="at">add=</span>T,<span class="at">cex=</span><span class="fl">0.4</span>)</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a><span class="co">#mf_label(map2ctr,var = "COM_NAME", col="blue",pos=1, cex=0.4, overlap=F)</span></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a><span class="fu">mf_map</span>(map1ctr,<span class="at">type=</span><span class="st">"base"</span>,<span class="at">pch=</span><span class="dv">15</span>,<span class="at">col=</span><span class="st">"red"</span>,<span class="at">add=</span>T, <span class="at">cex=</span><span class="fl">0.6</span>)</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a><span class="fu">mf_label</span>(map1ctr,<span class="at">var =</span> <span class="st">"COM_NAME"</span>, <span class="at">col=</span><span class="st">"red"</span>,<span class="at">pos=</span><span class="dv">1</span>,<span class="at">cex =</span> <span class="fl">0.5</span>,<span class="at">overlap =</span> F)</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a><span class="fu">mf_layout</span>(<span class="at">title =</span> <span class="st">"Communes et arrondissements du Borgou"</span>,</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>          <span class="at">credits =</span> <span class="st">"Source : EE CIST 2023"</span>,<span class="at">frame =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MOD1_Yquanti_005_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="576"></p>
</div>
</div>
</section>
<section id="urbainrural" class="level4">
<h4 class="anchored" data-anchor-id="urbainrural">Urbain/Rural</h4>
<p>L’attribution du caractère <em>urbain</em> ou <em>rural</em> à un arrondissement est le résultat d’une décision administrative de l’état. Elle se traduit dans le recensement de 2013 par l’ajout d’un code “5” en quatrième position du code de l’arrondissement. Il peut y avoir plusieurs arrondissements “urbains” à l’intérieur d’une même commune. Il peut également arriver que l’ensemble d’une commune soit composée d’arrondissements urbain comme c’est le cas pour Parakou. Les arrondissements urbains contigus portent en général le même nom suivi d’un numéro (PARAKOU 01, PARAKOU 02, PARAKOU 03, PARAKOU 04) et leur réunion forment implicitement une “ville” dans une logique administrative. Mais les contours de ces villes sont très différents de ceux que l’on pourrait obtenir par des sources non administratives telles que les images de télédétection utilisées par la base Africapolis où des données détaillées de mobilité à l’échelon indiviuel (non accessibles pour des raisons de secret statistique).</p>
<p>Qu’elle reflète ou non une réalité morphologique (continuité du bâti) ou fonctionnelle (solde migratoire positif) n’est cependant pas ici la question principale. En revanche il peut être intéressant de se demander si les arrondissements urbains bénéficient d’un traitement privilégié de l’état, conduisant par exemple celui-ci à mettre en place des politiques publiques qui privilégient ces lieux en matière de déploiement d’infrastructures (écoles, lycées, cliniques, …) ce qui peut attirer des populations plus riches ou plus éduquées, dotées d’un meilleur équipement.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>sel<span class="sc">$</span>URBA<span class="ot">&lt;-</span><span class="fu">as.factor</span>(sel<span class="sc">$</span>URBA)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(sel<span class="sc">$</span>URBA)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"Rural"</span>,<span class="st">"Urbain"</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>X<span class="ot">&lt;-</span>sel<span class="sc">$</span>URBA</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>Y<span class="ot">&lt;-</span>sel<span class="sc">$</span>equip</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>nameX<span class="ot">&lt;-</span><span class="st">"Catégorisation administrative de l'arrondissement"</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>nameY<span class="ot">&lt;-</span><span class="st">"Nombre d'équipements (0 à 24) "</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>titre<span class="ot">&lt;-</span><span class="st">"Equipement des ménages du Bénin en 2013"</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>source<span class="ot">&lt;-</span><span class="st">"Source : RP2013, INS Bénin"</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>mod<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X)</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Y<span class="sc">~</span>X, </span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">main=</span>titre,</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">sub =</span> source,</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab=</span>nameX,</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab=</span>nameY,</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>        <span class="at">col=</span><span class="st">"lightyellow"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MOD1_Yquanti_005_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.5341 -2.5341 -0.6171  1.3829 19.3829 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  3.61709    0.01551  233.22   &lt;2e-16 ***
XUrbain      1.91705    0.03268   58.67   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.19 on 54598 degrees of freedom
Multiple R-squared:  0.0593,    Adjusted R-squared:  0.05928 
F-statistic:  3442 on 1 and 54598 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><strong>Commentaire</strong> : La relation obtenue est très significative (p&lt;0.001) et son pouvoir explicatif est plutôt élevé (r2 = 6%) bien qu’inférieur à celui du nveau d’étude.</li>
</ul>
</section>
<section id="fonction-administrative" class="level4">
<h4 class="anchored" data-anchor-id="fonction-administrative">Fonction administrative</h4>
<p>Dans une logique légèrement différente, on peut se demander si les arrondissements qui remplissent des fonction de centralité administrative bénéficient d’un traitement privilégié de la part de l’état. Dans le cas du Bénin, tous les arrondissements qui sont centre de commune sont automatiquement déclarés urbains. Mais l’inverse n’est pas vrai et des arrondissements urbains peuvent ne pas être le siège d’un chef-lieu de commune ou de département.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>sel<span class="sc">$</span>CHEF<span class="ot">&lt;-</span><span class="fu">as.factor</span>(sel<span class="sc">$</span>COM_CHEF<span class="sc">+</span>sel<span class="sc">$</span>DEP_CHEF)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(sel<span class="sc">$</span>CHEF)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"Aucune"</span>,<span class="st">"Centre de commune"</span>, <span class="st">"Centre de département"</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>X<span class="ot">&lt;-</span>sel<span class="sc">$</span>CHEF</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>Y<span class="ot">&lt;-</span>sel<span class="sc">$</span>equip</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>nameX<span class="ot">&lt;-</span><span class="st">"Fonction administraive"</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>nameY<span class="ot">&lt;-</span><span class="st">"Nombre d'équipements (0 à 24) "</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>titre<span class="ot">&lt;-</span><span class="st">"Equipement des ménages du Bénin en 2013"</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>source<span class="ot">&lt;-</span><span class="st">"Source : RP2013, INS Bénin"</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>mod<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X)</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Y<span class="sc">~</span>X, </span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">main=</span>titre,</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">sub =</span> source,</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab=</span>nameX,</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab=</span>nameY,</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>        <span class="at">col=</span><span class="st">"lightyellow"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MOD1_Yquanti_005_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.2175 -1.9261 -0.9261  1.0739 20.0739 

Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)             3.92614    0.01509  260.27   &lt;2e-16 ***
XCentre de commune      0.60863    0.04324   14.08   &lt;2e-16 ***
XCentre de département  2.29136    0.09551   23.99   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.267 on 54597 degrees of freedom
Multiple R-squared:  0.01335,   Adjusted R-squared:  0.01331 
F-statistic: 369.4 on 2 and 54597 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><strong>Commentaire</strong> : La relation obtenue est très significative (p&lt;0.001) même si son pouvoir explicatif est plus limité (r2 = 1.3%) que celui de l’opposition urbain-rural . On note un net accroissement du niveau d’équipement des ménages avec le niveau administraif de l’arrondissement où ils sont localisés (+0.6 pour les ménages résidant dans un chef lieu de commune et +2.3 pourceux qui sont localisés dans un chef lieu de département)</li>
</ul>
</section>
<section id="accessibilité" class="level4">
<h4 class="anchored" data-anchor-id="accessibilité">Accessibilité</h4>
<p>Les <strong>déterminants spatiaux</strong> correspondent au cas où la variable explicative est de type <em>quantitatif continu</em> et où l’effet sur le ménage est lié à son <em>accessibilité</em> à une ressource c’est-à-dire à l’influence de la <em>distance</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>))</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>mypal<span class="ot">&lt;-</span><span class="fu">brewer.pal</span>(<span class="dv">8</span>,<span class="st">"RdYlGn"</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Distance à la commune</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>mybreaks<span class="ot">=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">8</span>,<span class="dv">16</span>,<span class="dv">32</span>,<span class="dv">64</span>,<span class="dv">128</span>)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="fu">mf_map</span>(map3,</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">type=</span><span class="st">"choro"</span>,</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">var=</span><span class="st">"COM_CHEF_DIST"</span>,</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">pal=</span>mypal,</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">breaks=</span>mybreaks,</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">border=</span><span class="st">"gray"</span>,</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">lwd=</span><span class="fl">0.3</span>,</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">leg_title =</span> <span class="st">"Distance(km)"</span>,</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">leg_val_rnd =</span> <span class="dv">0</span>)</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a><span class="fu">mf_map</span>(map2,<span class="at">type=</span><span class="st">"base"</span>,<span class="at">col=</span><span class="cn">NA</span>, <span class="at">border=</span><span class="st">"black"</span>,<span class="at">lwd=</span><span class="dv">2</span>, <span class="at">add=</span>T)</span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a><span class="fu">mf_map</span>(map2ctr,<span class="at">type=</span><span class="st">"base"</span>,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">col=</span><span class="st">"black"</span>,<span class="at">add=</span>T)</span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a><span class="fu">mf_label</span>(map2ctr,<span class="at">var =</span> <span class="st">"COM_NAME"</span>, <span class="at">col=</span><span class="st">"black"</span>,<span class="at">pos=</span><span class="dv">1</span>,<span class="at">cex=</span><span class="fl">0.6</span>)</span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a><span class="co">#mf_map(map1ctr,type="base",pch=20,col="black",add=T, cex=1)</span></span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a><span class="co">#mf_label(map1ctr,var = "DEP_NAME", col="black",pos=1)</span></span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a><span class="fu">mf_layout</span>(<span class="at">title =</span> <span class="st">"Accessibilité Communale"</span>,</span>
<span id="cb34-23"><a href="#cb34-23" aria-hidden="true" tabindex="-1"></a>          <span class="at">credits =</span> <span class="st">"Source : EE CIST 2023"</span>,<span class="at">frame =</span> T)</span>
<span id="cb34-24"><a href="#cb34-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-25"><a href="#cb34-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-26"><a href="#cb34-26" aria-hidden="true" tabindex="-1"></a><span class="do">## Distance au dept</span></span>
<span id="cb34-27"><a href="#cb34-27" aria-hidden="true" tabindex="-1"></a>mybreaks<span class="ot">=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">4</span>,<span class="dv">8</span>,<span class="dv">16</span>,<span class="dv">32</span>,<span class="dv">64</span>,<span class="dv">128</span>,<span class="dv">256</span>,<span class="dv">512</span>)</span>
<span id="cb34-28"><a href="#cb34-28" aria-hidden="true" tabindex="-1"></a><span class="fu">mf_map</span>(map3,</span>
<span id="cb34-29"><a href="#cb34-29" aria-hidden="true" tabindex="-1"></a>       <span class="at">type=</span><span class="st">"choro"</span>,</span>
<span id="cb34-30"><a href="#cb34-30" aria-hidden="true" tabindex="-1"></a>       <span class="at">var=</span><span class="st">"DEP_CHEF_DIST"</span>,</span>
<span id="cb34-31"><a href="#cb34-31" aria-hidden="true" tabindex="-1"></a>       <span class="at">pal=</span>mypal,</span>
<span id="cb34-32"><a href="#cb34-32" aria-hidden="true" tabindex="-1"></a>       <span class="at">breaks=</span>mybreaks,</span>
<span id="cb34-33"><a href="#cb34-33" aria-hidden="true" tabindex="-1"></a>        <span class="at">border=</span><span class="st">"gray"</span>,</span>
<span id="cb34-34"><a href="#cb34-34" aria-hidden="true" tabindex="-1"></a>       <span class="at">lwd=</span><span class="dv">1</span>,</span>
<span id="cb34-35"><a href="#cb34-35" aria-hidden="true" tabindex="-1"></a>       <span class="at">leg_title =</span> <span class="st">"Distance (km)"</span>,</span>
<span id="cb34-36"><a href="#cb34-36" aria-hidden="true" tabindex="-1"></a>       <span class="at">leg_val_rnd =</span> <span class="dv">0</span>)</span>
<span id="cb34-37"><a href="#cb34-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-38"><a href="#cb34-38" aria-hidden="true" tabindex="-1"></a><span class="co">#mf_map(map2,type="base",col=NA, border="black",lwd=1, add=T)</span></span>
<span id="cb34-39"><a href="#cb34-39" aria-hidden="true" tabindex="-1"></a><span class="fu">mf_map</span>(map1,<span class="at">type=</span><span class="st">"base"</span>,<span class="at">col=</span><span class="cn">NA</span>, <span class="at">border=</span><span class="st">"black"</span>,<span class="at">lwd=</span><span class="dv">2</span>, <span class="at">add=</span>T)</span>
<span id="cb34-40"><a href="#cb34-40" aria-hidden="true" tabindex="-1"></a><span class="fu">mf_map</span>(map1ctr,<span class="at">type=</span><span class="st">"base"</span>,<span class="at">pch=</span><span class="dv">15</span>,<span class="at">col=</span><span class="st">"black"</span>,<span class="at">add=</span>T, <span class="at">cex=</span><span class="dv">1</span>)</span>
<span id="cb34-41"><a href="#cb34-41" aria-hidden="true" tabindex="-1"></a><span class="fu">mf_label</span>(map1ctr,<span class="at">var =</span> <span class="st">"DEP_NAME"</span>, <span class="at">col=</span><span class="st">"black"</span>,<span class="at">pos=</span><span class="dv">1</span>)</span>
<span id="cb34-42"><a href="#cb34-42" aria-hidden="true" tabindex="-1"></a><span class="fu">mf_layout</span>(<span class="at">title =</span> <span class="st">"Accessibilité Départementale"</span>,</span>
<span id="cb34-43"><a href="#cb34-43" aria-hidden="true" tabindex="-1"></a>          <span class="at">credits =</span> <span class="st">"Source : EE CIST 2023"</span>,<span class="at">frame =</span> T)</span>
<span id="cb34-44"><a href="#cb34-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-45"><a href="#cb34-45" aria-hidden="true" tabindex="-1"></a><span class="do">## Distance à la capitale nationale</span></span>
<span id="cb34-46"><a href="#cb34-46" aria-hidden="true" tabindex="-1"></a>map0ctr<span class="ot">&lt;-</span><span class="fu">st_centroid</span>(map3[map3<span class="sc">$</span>NAT_CHEF_DIST<span class="sc">==</span><span class="dv">0</span>,])</span>
<span id="cb34-47"><a href="#cb34-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-48"><a href="#cb34-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-49"><a href="#cb34-49" aria-hidden="true" tabindex="-1"></a>mybreaks<span class="ot">=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">8</span>,<span class="dv">16</span>,<span class="dv">32</span>,<span class="dv">64</span>,<span class="dv">128</span>,<span class="dv">256</span>,<span class="dv">512</span>,<span class="dv">1024</span>)</span>
<span id="cb34-50"><a href="#cb34-50" aria-hidden="true" tabindex="-1"></a><span class="fu">mf_map</span>(map3,</span>
<span id="cb34-51"><a href="#cb34-51" aria-hidden="true" tabindex="-1"></a>       <span class="at">type=</span><span class="st">"choro"</span>,</span>
<span id="cb34-52"><a href="#cb34-52" aria-hidden="true" tabindex="-1"></a>       <span class="at">var=</span><span class="st">"NAT_CHEF_DIST"</span>,</span>
<span id="cb34-53"><a href="#cb34-53" aria-hidden="true" tabindex="-1"></a>       <span class="at">pal=</span>mypal,</span>
<span id="cb34-54"><a href="#cb34-54" aria-hidden="true" tabindex="-1"></a>       <span class="at">breaks=</span>mybreaks,</span>
<span id="cb34-55"><a href="#cb34-55" aria-hidden="true" tabindex="-1"></a>        <span class="at">border=</span><span class="st">"gray"</span>,</span>
<span id="cb34-56"><a href="#cb34-56" aria-hidden="true" tabindex="-1"></a>       <span class="at">lwd=</span><span class="dv">1</span>,</span>
<span id="cb34-57"><a href="#cb34-57" aria-hidden="true" tabindex="-1"></a>       <span class="at">leg_title =</span> <span class="st">"Distance (km)"</span>,</span>
<span id="cb34-58"><a href="#cb34-58" aria-hidden="true" tabindex="-1"></a>       <span class="at">leg_val_rnd =</span> <span class="dv">0</span>)</span>
<span id="cb34-59"><a href="#cb34-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-60"><a href="#cb34-60" aria-hidden="true" tabindex="-1"></a><span class="co">#mf_map(map2,type="base",col=NA, border="black",lwd=1, add=T)</span></span>
<span id="cb34-61"><a href="#cb34-61" aria-hidden="true" tabindex="-1"></a><span class="fu">mf_map</span>(map0,<span class="at">type=</span><span class="st">"base"</span>,<span class="at">col=</span><span class="cn">NA</span>, <span class="at">border=</span><span class="st">"black"</span>,<span class="at">lwd=</span><span class="dv">2</span>, <span class="at">add=</span>T)</span>
<span id="cb34-62"><a href="#cb34-62" aria-hidden="true" tabindex="-1"></a><span class="fu">mf_map</span>(map0ctr,<span class="at">type=</span><span class="st">"base"</span>,<span class="at">pch=</span><span class="dv">15</span>,<span class="at">col=</span><span class="st">"black"</span>,<span class="at">add=</span>T, <span class="at">cex=</span><span class="dv">2</span>)</span>
<span id="cb34-63"><a href="#cb34-63" aria-hidden="true" tabindex="-1"></a><span class="fu">mf_label</span>(map0ctr,<span class="at">var =</span> <span class="st">"COM_NAME"</span>, <span class="at">col=</span><span class="st">"black"</span>,<span class="at">pos=</span><span class="dv">1</span>)</span>
<span id="cb34-64"><a href="#cb34-64" aria-hidden="true" tabindex="-1"></a><span class="fu">mf_layout</span>(<span class="at">title =</span> <span class="st">"Accessibilité Nationale"</span>,</span>
<span id="cb34-65"><a href="#cb34-65" aria-hidden="true" tabindex="-1"></a>          <span class="at">credits =</span> <span class="st">"Source : EE CIST 2023"</span>,<span class="at">frame =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MOD1_Yquanti_005_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="864"></p>
</div>
</div>
</section>
</section>
<section id="accessibilité-communale" class="level3">
<h3 class="anchored" data-anchor-id="accessibilité-communale">Accessibilité communale</h3>
<p>On utilise une fonction racine carré pour modéliser l’effet de la distance. Pour une distance égale à zéro, la constante donnera l’effet du chefl-lieu de commune.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>sel<span class="sc">$</span>ACC_COM<span class="ot">&lt;-</span><span class="fu">sqrt</span>(sel<span class="sc">$</span>COM_CHEF_DIST)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>X<span class="ot">&lt;-</span>sel<span class="sc">$</span>ACC_COM</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>Y<span class="ot">&lt;-</span>sel<span class="sc">$</span>equip</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>nameX<span class="ot">&lt;-</span><span class="st">"Distance au centre de la commune (racine carrée)"</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>nameY<span class="ot">&lt;-</span><span class="st">"Nombre d'équipements (0 à 24) "</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>titre<span class="ot">&lt;-</span><span class="st">"Equipement des ménages du Bénin en 2013"</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>source<span class="ot">&lt;-</span><span class="st">"Source : RP2013, INS Bénin"</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>mod<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X)</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(X,Y ,</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch=</span><span class="dv">20</span>,</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex=</span><span class="fl">0.4</span>,</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">main=</span>titre,</span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">sub =</span> source,</span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab=</span>nameX,</span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab=</span>nameY)</span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(mod, <span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MOD1_Yquanti_005_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X)

Residuals:
   Min     1Q Median     3Q    Max 
-4.838 -2.245 -0.773  1.417 20.247 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.838526   0.028328  170.81   &lt;2e-16 ***
X           -0.257530   0.008043  -32.02   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.258 on 54598 degrees of freedom
Multiple R-squared:  0.01843,   Adjusted R-squared:  0.01842 
F-statistic:  1025 on 1 and 54598 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><strong>Commentaire</strong> : La relation obtenue est très significative (p&lt;0.001) même si son pouvoir explicatif est plus limité (r2 = 1.8%). Ceci s’explique tout d’abord par l’incertitude de mesure : la distance utilisée est l’éloignement entre les arrondissements et non pas entre l’individu et le centre de sa commune. Mais aussi par la diversité des ménages en matière d’équipement quelle que soit la distance au centre.</li>
</ul>
</section>
<section id="accessibilité-départementale" class="level3">
<h3 class="anchored" data-anchor-id="accessibilité-départementale">Accessibilité départementale</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>sel<span class="sc">$</span>ACC_DEP<span class="ot">&lt;-</span><span class="fu">sqrt</span>(sel<span class="sc">$</span>DEP_CHEF_DIST)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>X<span class="ot">&lt;-</span>sel<span class="sc">$</span>ACC_DEP</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>Y<span class="ot">&lt;-</span>sel<span class="sc">$</span>equip</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>nameX<span class="ot">&lt;-</span><span class="st">"Distance au centre du département (racine carrée)"</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>nameY<span class="ot">&lt;-</span><span class="st">"Nombre d'équipements (0 à 24) "</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>titre<span class="ot">&lt;-</span><span class="st">"Equipement des ménages du Bénin en 2013"</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>source<span class="ot">&lt;-</span><span class="st">"Source : RP2013, INS Bénin"</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>mod<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X)</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(X,Y ,</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch=</span><span class="dv">20</span>,</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex=</span><span class="fl">0.4</span>,</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">main=</span>titre,</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">sub =</span> source,</span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab=</span>nameX,</span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab=</span>nameY)</span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(mod, <span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MOD1_Yquanti_005_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.8445 -2.2733 -0.7454  1.4512 19.7786 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.844517   0.035941  134.79   &lt;2e-16 ***
X           -0.147858   0.006152  -24.03   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.272 on 54598 degrees of freedom
Multiple R-squared:  0.01047,   Adjusted R-squared:  0.01045 
F-statistic: 577.6 on 1 and 54598 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><strong>Commentaire</strong> : La relation obtenue demeure très significative (p&lt;0.001) mais son pouvoir explicatif demeure limité (r2 = 1.0%).</li>
</ul>
</section>
<section id="accessibilité-nationale" class="level3">
<h3 class="anchored" data-anchor-id="accessibilité-nationale">Accessibilité Nationale</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>sel<span class="sc">$</span>ACC_NAT<span class="ot">&lt;-</span><span class="fu">sqrt</span>(sel<span class="sc">$</span>NAT_CHEF_DIST)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>X<span class="ot">&lt;-</span>sel<span class="sc">$</span>ACC_NAT</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>Y<span class="ot">&lt;-</span>sel<span class="sc">$</span>equip</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>nameX<span class="ot">&lt;-</span><span class="st">"Distance à la capitale nationale (racine carrée)"</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>nameY<span class="ot">&lt;-</span><span class="st">"Nombre d'équipements (0 à 24) "</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>titre<span class="ot">&lt;-</span><span class="st">"Equipement des ménages du Bénin en 2013"</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>source<span class="ot">&lt;-</span><span class="st">"Source : RP2013, INS Bénin"</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>mod<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X)</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(X,Y ,</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch=</span><span class="dv">20</span>,</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex=</span><span class="fl">0.4</span>,</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">main=</span>titre,</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">sub =</span> source,</span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab=</span>nameX,</span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab=</span>nameY)</span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(mod, <span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MOD1_Yquanti_005_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.4562 -2.2186 -0.7569  1.3006 20.1477 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.45623    0.03081  144.66   &lt;2e-16 ***
X           -0.03313    0.00223  -14.86   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.282 on 54598 degrees of freedom
Multiple R-squared:  0.004025,  Adjusted R-squared:  0.004007 
F-statistic: 220.7 on 1 and 54598 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><strong>Commentaire</strong> : La relation obtenue est très significative (p&lt;0.001) même si son pouvoir explicatif est très limité (r2 = 0.4%). Il faut toutefois examiner le rôle de ces variables d’accessibilité lorsqu’on les combine avec les autres variables relatives aux ménages.</li>
</ul>
</section>
<section id="synthese" class="level3">
<h3 class="anchored" data-anchor-id="synthese">SYNTHESE</h3>
<section id="variables-endogène" class="level4">
<h4 class="anchored" data-anchor-id="variables-endogène">Variables endogène</h4>
<p>On en retient d’abord que les variables relatives à la structure du ménage et aux attributs du chef de ménage.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>mod1<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>sel, equip<span class="sc">~</span><span class="fu">log</span>(tailmen)<span class="sc">+</span>statoc<span class="sc">+</span>sexe<span class="sc">+</span>age5<span class="sc">+</span>etud5)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = equip ~ log(tailmen) + statoc + sexe + age5 + etud5, 
    data = sel)

Residuals:
     Min       1Q   Median       3Q      Max 
-11.0754  -1.8455  -0.4329   1.3331  20.6140 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        1.67591    0.05409  30.982  &lt; 2e-16 ***
log(tailmen)       0.88914    0.02415  36.820  &lt; 2e-16 ***
statocPropFam     -0.55877    0.02692 -20.756  &lt; 2e-16 ***
statocAutre       -0.42373    0.06566  -6.454 1.10e-10 ***
statocLocat        1.14917    0.05016  22.910  &lt; 2e-16 ***
sexeF             -0.83280    0.03520 -23.660  &lt; 2e-16 ***
age530-39          0.36677    0.03797   9.659  &lt; 2e-16 ***
age540-49          0.37145    0.04077   9.111  &lt; 2e-16 ***
age550-59          0.50248    0.04589  10.949  &lt; 2e-16 ***
age560+            0.28754    0.04506   6.381 1.78e-10 ***
etud52.Primaire    1.32687    0.03163  41.944  &lt; 2e-16 ***
etud53.Secondaire  3.05137    0.03697  82.528  &lt; 2e-16 ***
etud54.Supérieur   6.00856    0.07763  77.400  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.829 on 54587 degrees of freedom
Multiple R-squared:  0.2604,    Adjusted R-squared:  0.2603 
F-statistic:  1602 on 12 and 54587 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(mod1, <span class="at">type=</span><span class="st">"III"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: equip
             Sum Sq    Df F value    Pr(&gt;F)    
(Intercept)    7680     1  959.89 &lt; 2.2e-16 ***
log(tailmen)  10847     1 1355.71 &lt; 2.2e-16 ***
statoc        11767     3  490.21 &lt; 2.2e-16 ***
sexe           4479     1  559.80 &lt; 2.2e-16 ***
age5           1136     4   35.50 &lt; 2.2e-16 ***
etud5         91359     3 3806.05 &lt; 2.2e-16 ***
Residuals    436762 54587                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li><strong>Commentaire</strong> : la combinaison des déterminants sociaux aboutit à un modèle satisfaisant (r2=26%) où toutes les variables apportent une contribution significative au modèle. L’analyse de variance de type III (toutes choses égales par ailleurs) confirme le rôle central du niveau de diplôme du chef de ménage qui est de lion la variable qui contribue le plus à l’explication du niveau d’équipement. La taille du ménage joue également un rôle important ainsi que le statut d’occupation qui montre un meilleur équipement des locataires.L’influence de l’âge et du sexe est plus limitée.</li>
</ul>
</section>
<section id="variables-contextuelles" class="level4">
<h4 class="anchored" data-anchor-id="variables-contextuelles">Variables contextuelles</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>mod2<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>sel, equip<span class="sc">~</span>URBA<span class="sc">+</span>ACC_COM<span class="sc">+</span>ACC_DEP<span class="sc">+</span>ACC_NAT)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = equip ~ URBA + ACC_COM + ACC_DEP + ACC_NAT, data = sel)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.3603 -2.3168 -0.6018  1.4378 19.8409 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  3.636340   0.047536   76.50   &lt;2e-16 ***
URBAUrbain   2.428247   0.046287   52.46   &lt;2e-16 ***
ACC_COM      0.221386   0.012150   18.22   &lt;2e-16 ***
ACC_DEP     -0.077063   0.007326  -10.52   &lt;2e-16 ***
ACC_NAT     -0.032419   0.002778  -11.67   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.174 on 54595 degrees of freedom
Multiple R-squared:  0.06866,   Adjusted R-squared:  0.06859 
F-statistic:  1006 on 4 and 54595 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(mod2, <span class="at">type=</span><span class="st">"III"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: equip
            Sum Sq    Df F value    Pr(&gt;F)    
(Intercept)  58954     1 5851.74 &lt; 2.2e-16 ***
URBA         27726     1 2752.11 &lt; 2.2e-16 ***
ACC_COM       3345     1  331.99 &lt; 2.2e-16 ***
ACC_DEP       1115     1  110.65 &lt; 2.2e-16 ***
ACC_NAT       1372     1  136.15 &lt; 2.2e-16 ***
Residuals   550021 54595                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li><strong>Commentaire : </strong> le mélange des variables contextuelles est difficile à interpréter en raison des fortes redondances qu’il y a entre certaines variables explicatives. En effet la variable URBA est corrélée avec le fait d’être ou pas un centre de commune ou de département. MAlgré son pouvoir explicatif limité (r2=6.9%) le modèle met bien en valeur la combinaison des différents effets d’urbanisation et d’accessibilité. On note une inversion de l’effet d’accessibilité au chef lieu de commune qui s’explique par l’ajout des deux autres variables d’accessibilité.</li>
</ul>
</section>
<section id="variables-endogènes-et-contextuelles" class="level4">
<h4 class="anchored" data-anchor-id="variables-endogènes-et-contextuelles">Variables endogènes et contextuelles</h4>
<p>On construit un modèle final reprenant l’ensemble des variables endogènes mais en leur ajoutant les deux mesures d’accessibilité a au centre de commune ou de district.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>mod3<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>sel, equip<span class="sc">~</span><span class="fu">log</span>(tailmen)<span class="sc">+</span>statoc<span class="sc">+</span>sexe<span class="sc">+</span>age5<span class="sc">+</span>etud5<span class="sc">+</span>URBA<span class="sc">+</span>ACC_COM<span class="sc">+</span>ACC_DEP<span class="sc">+</span>ACC_NAT)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = equip ~ log(tailmen) + statoc + sexe + age5 + etud5 + 
    URBA + ACC_COM + ACC_DEP + ACC_NAT, data = sel)

Residuals:
     Min       1Q   Median       3Q      Max 
-11.2365  -1.8215  -0.3934   1.3575  20.6885 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        1.605216   0.066453  24.155  &lt; 2e-16 ***
log(tailmen)       0.988396   0.024501  40.342  &lt; 2e-16 ***
statocPropFam     -0.585553   0.026798 -21.851  &lt; 2e-16 ***
statocAutre       -0.537254   0.064720  -8.301  &lt; 2e-16 ***
statocLocat        0.707877   0.050480  14.023  &lt; 2e-16 ***
sexeF             -0.922920   0.034873 -26.465  &lt; 2e-16 ***
age530-39          0.292758   0.037436   7.820 5.37e-15 ***
age540-49          0.259819   0.040264   6.453 1.11e-10 ***
age550-59          0.362171   0.045334   7.989 1.39e-15 ***
age560+            0.147358   0.044516   3.310 0.000933 ***
etud52.Primaire    1.143840   0.031894  35.864  &lt; 2e-16 ***
etud53.Secondaire  2.769215   0.037352  74.137  &lt; 2e-16 ***
etud54.Supérieur   5.556467   0.077327  71.857  &lt; 2e-16 ***
URBAUrbain         1.496127   0.042144  35.500  &lt; 2e-16 ***
ACC_COM            0.149466   0.010709  13.957  &lt; 2e-16 ***
ACC_DEP           -0.056129   0.006468  -8.678  &lt; 2e-16 ***
ACC_NAT           -0.028252   0.002533 -11.153  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.784 on 54583 degrees of freedom
Multiple R-squared:  0.2837,    Adjusted R-squared:  0.2835 
F-statistic:  1351 on 16 and 54583 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(mod3, <span class="at">type=</span><span class="st">"III"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: equip
             Sum Sq    Df  F value    Pr(&gt;F)    
(Intercept)    4522     1  583.488 &lt; 2.2e-16 ***
log(tailmen)  12613     1 1627.460 &lt; 2.2e-16 ***
statoc         7867     3  338.377 &lt; 2.2e-16 ***
sexe           5428     1  700.421 &lt; 2.2e-16 ***
age5            686     4   22.123 &lt; 2.2e-16 ***
etud5         70895     3 3049.204 &lt; 2.2e-16 ***
URBA           9767     1 1260.251 &lt; 2.2e-16 ***
ACC_COM        1510     1  194.785 &lt; 2.2e-16 ***
ACC_DEP         584     1   75.309 &lt; 2.2e-16 ***
ACC_NAT         964     1  124.385 &lt; 2.2e-16 ***
Residuals    423023 54583                       
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li><strong>Commentaire</strong> : Par rapport au modèle purement endogène de modélistion des comportements individuels par les attributs des ménages, le gain est assez faible en terme de qualité d’ajustement (passage de 26% à 28.3%). C’est plutôt au niveau de l’interprétation que le nouveau modèle est intéressant car il révèle que le niveau d’étude se combine étroitement dans l’explication avec l’accessibilité aux centres de commune ou de districts. Ce qui laisse soupçonner une interaction entre les deux facteurs</li>
</ul>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>